import React from 'react'

export default function HomePage(props){
    return (
        <div>
            <p>Mariola to aplikacja pozwalajaca na wymiany grup w poszczegolnych przedmiotach.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ornare nisl molestie, eleifend mi ut, tempus lorem. Donec a placerat nisi, at porta quam. Suspendisse non pretium ex. Nam ultrices, eros a mattis feugiat, arcu augue rutrum justo, sed ultrices lacus lorem et est. Etiam viverra, elit quis rhoncus auctor, leo enim pretium est, ut tincidunt lorem nunc a nulla. Integer accumsan, est bibendum vulputate consectetur, lorem turpis condimentum massa, ac euismod eros metus et dui. Maecenas vestibulum consectetur sem, nec fermentum augue ultricies eget. Nullam vulputate, dolor et interdum tempor, odio urna feugiat leo, at blandit mauris elit vel risus. Ut turpis enim, rhoncus in mauris quis, lobortis dignissim lorem. Sed metus ipsum, efficitur id sem eu, posuere egestas lorem. Etiam feugiat nec orci condimentum blandit. Aliquam rutrum nisi nunc, quis molestie nunc convallis in. Ut venenatis orci lorem, non elementum mauris consequat at.</p>
            <p>Curabitur ullamcorper, libero ac blandit fermentum, est dui vehicula purus, et condimentum massa dolor ut est. Donec nec leo sollicitudin augue ornare finibus quis dignissim mauris. Aenean sed elementum leo. Aenean in mattis ex. Vivamus vulputate auctor pretium. Maecenas maximus rutrum sodales. Aliquam molestie a elit non vestibulum. Donec tincidunt quam id consequat sollicitudin. Morbi eget lectus leo. Quisque nisl massa, pharetra ac gravida eget, fringilla in est.</p>
            <p>Quisque eget facilisis mauris. Sed auctor faucibus lorem id hendrerit. Nulla ac leo sem. Nunc ex lacus, viverra vitae feugiat vitae, rutrum id leo. Phasellus diam arcu, dignissim at nulla non, imperdiet dignissim dui. Nam in tortor felis. Etiam eget tortor pulvinar, placerat metus ac, iaculis leo. Donec ac leo venenatis, scelerisque tellus ac, mattis libero. Nullam suscipit tempor sagittis. Nulla in ipsum nisl. Mauris fringilla felis a arcu ultricies ultrices. Etiam eu feugiat ante.</p>
            <p>Donec varius lorem sed ullamcorper faucibus. Aliquam id dictum mi. Aliquam pharetra nec magna sit amet aliquam. Vestibulum pellentesque nulla in urna elementum convallis. Phasellus tempus dui sed dolor tempor pharetra. Vestibulum malesuada neque dolor, vitae pharetra libero facilisis in. Nam a eros in neque auctor euismod sit amet eget nulla. Nulla facilisi.</p>
            <p>Cras nec odio interdum, consequat eros eu, varius dui. Donec sed vestibulum magna, nec fermentum felis. Vivamus sagittis eget dui eget rutrum. Donec malesuada turpis et maximus pharetra. Pellentesque interdum lectus vel nisl elementum, ac accumsan nisi tincidunt. Pellentesque hendrerit leo enim, vitae interdum neque condimentum quis. Ut rutrum turpis a ex rutrum ultricies. Pellentesque rutrum nulla velit, eu fringilla mauris pulvinar in. Duis malesuada cursus eros, non finibus urna tincidunt sed.</p>
        </div>
    )
}